import { Metric, Review, MenuItem, IntegrationStatus, Language } from './types';

// ── language switcher ───────────────────────────────────────────────────────

const LANG_CYCLE: Language[] = ['ru', 'en', 'uz'];

export function nextLang(lang: Language): Language {
  return LANG_CYCLE[(LANG_CYCLE.indexOf(lang) + 1) % LANG_CYCLE.length];
}

/** Pick a string for the active language. Use for ad-hoc inline strings outside TRANSLATIONS. */
export function tr(lang: Language, ru: string, en: string, uz: string): string {
  return lang === 'ru' ? ru : lang === 'uz' ? uz : en;
}

/** Format minutes as "42m" / "1h 05m" once past an hour — used everywhere a
 *  duration is shown so long waits/tickets/cook times read as hours, not a
 *  three-digit minute count. */
export function formatMinutes(min: number, lang: Language): string {
  const m = Math.max(0, Math.round(min));
  if (m < 60) return tr(lang, `${m} мин`, `${m}m`, `${m} daq`);
  const h = Math.floor(m / 60);
  const rem = m % 60;
  const remStr = String(rem).padStart(2, '0');
  return tr(lang, `${h}ч ${remStr}м`, `${h}h ${remStr}m`, `${h}s ${remStr}daq`);
}

/** Compact variant for tight badges/pills: "42м" / "1ч05" — no space, no unit suffix repeats. */
export function formatMinutesShort(min: number, lang: Language): string {
  const m = Math.max(0, Math.round(min));
  if (m < 60) return tr(lang, `${m}м`, `${m}m`, `${m}d`);
  const h = Math.floor(m / 60);
  const rem = String(m % 60).padStart(2, '0');
  return `${h}${tr(lang, 'ч', 'h', 's')}${rem}`;
}

// ── iiko-sourced mock data ──────────────────────────────────────────────────

export const CASH_SHIFT = {
  id: 'SH-0142',
  cashier: 'Дмитрий В.',
  opened: '09:00',
  revenue: 3_810_000,
  orders: 47,
  cash: 1_290_000,
  card: 2_520_000,
  collections: 1,
  status: 'open' as 'open' | 'closed',
};

export const STOP_LIST = [
  { id: '1', name: 'Ribeye Steak 400g', category: 'Гриль', stoppedAt: '13:42', reason: 'Нет в наличии' },
  { id: '2', name: 'Truffle Burger', category: 'Бургеры', stoppedAt: '11:15', reason: 'Нет заготовки' },
  { id: '3', name: 'Tom Kha Soup', category: 'Супы', stoppedAt: '10:30', reason: 'Нет кокосового молока' },
];

export const ACTIVE_ORDERS = [
  { id: 'ORD-081', table: 'Стол 4', waiter: 'Alex K.', items: 3, openedAt: '14:02', ticketMin: 22, status: 'cooking' as const },
  { id: 'ORD-082', table: 'Стол 7', waiter: 'Maria S.', items: 5, openedAt: '14:18', ticketMin: 6, status: 'waiting' as const },
  { id: 'ORD-083', table: 'Бар 2', waiter: 'Dmitry V.', items: 2, openedAt: '14:21', ticketMin: 3, status: 'ready' as const },
  { id: 'ORD-084', table: 'Стол 12', waiter: 'Elena R.', items: 4, openedAt: '14:25', ticketMin: 1, status: 'cooking' as const },
  { id: 'ORD-085', table: 'Стол 9', waiter: 'Alex K.', items: 6, openedAt: '14:28', ticketMin: 8, status: 'waiting' as const },
];

export const SUPPLY_INVOICES = [
  { id: 'ПН-1042', supplier: 'Мирзо Агро', date: '15.04.2026', items: 12, amount: 5_650_000, status: 'posted' as const },
  { id: 'ПН-1041', supplier: 'ФудМаркет', date: '14.04.2026', items: 8,  amount: 3_280_000, status: 'posted' as const },
  { id: 'ПН-1040', supplier: 'Алко Трейд', date: '13.04.2026', items: 5,  amount: 2_470_000, status: 'posted' as const },
  { id: 'ПН-1039', supplier: 'Мирзо Агро', date: '12.04.2026', items: 14, amount: 6_940_000, status: 'draft' as const },
  { id: 'ПН-1038', supplier: 'МясоОптом', date: '11.04.2026', items: 3,  amount: 4_850_000, status: 'posted' as const },
];

export const WRITEOFFS = [
  { id: 'АС-0318', name: 'Ribeye 400g', qty: 2, unit: 'шт', cost: 148_000, reason: 'Брак', date: '15.04 12:41', staff: 'Дмитрий В.' },
  { id: 'АС-0317', name: 'Кокосовое молоко 1L', qty: 3, unit: 'шт', cost: 46_000, reason: 'Истёк срок', date: '15.04 10:18', staff: 'Elena R.' },
  { id: 'АС-0316', name: 'Форель охл. кг', qty: 0.5, unit: 'кг', cost: 58_000, reason: 'Брак', date: '14.04 19:05', staff: 'Maria S.' },
  { id: 'АС-0315', name: 'Авокадо', qty: 4, unit: 'шт', cost: 28_000, reason: 'Перезрел', date: '14.04 09:30', staff: 'Alex K.' },
];

export const INVENTORY_SUMMARY = {
  date: '14.04.2026',
  staff: 'Maria S.',
  totalItems: 148,
  matched: 134,
  surplus: 8,
  shortage: 6,
  shortageAmount: 340_000,
};

// Revenue = price × weekly orders; shares = item_revenue / total_weekly_revenue (~180M)
export const ABC_ANALYSIS = [
  { name: 'Ribeye Steak',          cat: 'Гриль',    abc: 'A', revenue: 26_825_000, share: 14.9, orders: 145, margin: 68 },
  { name: 'Caesar Salad',           cat: 'Салаты',   abc: 'A', revenue: 20_800_000, share: 11.5, orders: 320, margin: 72 },
  { name: 'Passion Fruit Lemonade', cat: 'Напитки',  abc: 'A', revenue: 15_750_000, share: 8.7,  orders: 450, margin: 85 },
  { name: 'Truffle Burger',         cat: 'Горячее',  abc: 'A', revenue: 20_700_000, share: 11.5, orders: 180, margin: 61 },
  { name: 'Tom Yum',                cat: 'Супы',     abc: 'B', revenue: 15_750_000, share: 8.7,  orders: 210, margin: 74 },
  { name: 'Mojito',                 cat: 'Напитки',  abc: 'B', revenue: 15_950_000, share: 8.8,  orders: 290, margin: 82 },
  { name: 'Greek Salad',            cat: 'Салаты',   abc: 'B', revenue: 10_880_000, share: 6.0,  orders: 160, margin: 71 },
  { name: 'Pasta Carbonara',        cat: 'Горячее',  abc: 'B', revenue: 11_040_000, share: 6.1,  orders: 120, margin: 66 },
  { name: 'Cheesecake',             cat: 'Десерты',  abc: 'C', revenue: 4_160_000,  share: 2.3,  orders: 80,  margin: 77 },
  { name: 'Espresso',               cat: 'Кофе',     abc: 'C', revenue: 2_400_000,  share: 1.3,  orders: 120, margin: 88 },
];

// Sum = 10,680,000 UZS = METRICS total_revenue for today (89 guests × 120,000 avg check)
export const HOURLY_REVENUE = [
  { h: '10', rev:   129_000, orders:   6 },
  { h: '11', rev:   303_000, orders:  13 },
  { h: '12', rev:   681_000, orders:  28 },
  { h: '13', rev: 1_062_000, orders:  42 },
  { h: '14', rev:   947_000, orders:  38 },
  { h: '15', rev:   559_000, orders:  24 },
  { h: '16', rev:   387_000, orders:  16 },
  { h: '17', rev:   631_000, orders:  27 },
  { h: '18', rev: 1_162_000, orders:  48 },
  { h: '19', rev: 1_506_000, orders:  58 },
  { h: '20', rev: 1_420_000, orders:  54 },
  { h: '21', rev: 1_262_000, orders:  49 },
  { h: '22', rev:   631_000, orders:  25 },
];

export const CATEGORY_REVENUE = [
  { name: 'Гриль',   value: 42, color: '#ff6b35' },
  { name: 'Напитки', value: 22, color: '#f59e0b' },
  { name: 'Горячее', value: 16, color: '#3b82f6' },
  { name: 'Салаты',  value: 12, color: '#22c55e' },
  { name: 'Прочее',  value: 8,  color: '#6b7280' },
];

// Base = today. avg_check = 10,680,000 / 89 = 120,000 UZS ≈ $9.45 (mid-upscale Tashkent) ✓
export const METRICS: Metric[] = [
  { label: 'total_revenue', value: '10,680,000 UZS', change: 12.5, trend: 'up', isCurrency: true },
  { label: 'avg_check',     value: '120,000 UZS',    change: 3.2,  trend: 'up', isCurrency: true },
  { label: 'guests_count',  value: '89',            change: 8.7,  trend: 'up', isCurrency: false },
  { label: 'food_cost',     value: '28.4%',         change: 0.5,  trend: 'down', isCurrency: false },
  { label: 'labor_cost',    value: '22.1%',         change: -0.8, trend: 'up', isCurrency: false },
  { label: 'nps_score',     value: '72',            change: 5.0,  trend: 'up', isCurrency: false },
  { label: 'review_rating', value: '4.8',           change: 0.1,  trend: 'up', isCurrency: false },
];

export const INTEGRATIONS: IntegrationStatus[] = [
  { id: '1', name: 'iiko Cloud', status: 'connected', lastSync: '1 min ago', type: 'POS' },
];

export const REVIEWS: Review[] = [
  { id: '1', author: 'Алексей Петров', platform: 'Google', rating: 5, date: '2h ago', text: 'Отличная атмосфера и вкусные стейки! Обязательно вернемся.', sentiment: 'positive' },
  { id: '2', author: 'Мария Иванова', platform: 'Yandex', rating: 4, date: 'Yesterday', text: 'Еда вкусная, но пришлось долго ждать официанта.', sentiment: 'neutral' },
  { id: '3', author: 'Dmitry K.', platform: 'TripAdvisor', rating: 5, date: '2d ago', text: 'Best cocktails in the city, the atmosphere is unmatched!', sentiment: 'positive' },
  { id: '4', author: 'Елена С.', platform: '2GIS', rating: 2, date: '3d ago', text: 'Шумно и пересолили суп.', sentiment: 'negative' },
];

// Prices in UZS (~1 USD = 12,700 UZS). Revenue = price × weekly orders.
export const TOP_DISHES: MenuItem[] = [
  { id: '1', name: 'Ribeye Steak',          category: 'Grill',  price: 185_000, orders: 145, revenue: 26_825_000, trend: 'up',   inStock: true  },
  { id: '2', name: 'Caesar Salad',           category: 'Salads', price:  65_000, orders: 320, revenue: 20_800_000, trend: 'up',   inStock: true  },
  { id: '3', name: 'Tom Yum',                category: 'Soups',  price:  75_000, orders: 210, revenue: 15_750_000, trend: 'down', inStock: true  },
  { id: '4', name: 'Passion Fruit Lemonade', category: 'Drinks', price:  35_000, orders: 450, revenue: 15_750_000, trend: 'up',   inStock: true  },
  { id: '5', name: 'Truffle Burger',         category: 'Main',   price: 115_000, orders: 180, revenue: 20_700_000, trend: 'up',   inStock: false },
];

// Sun (today) = 10,680,000 UZS; visitors Sun = 89; avg_check = 120,000 UZS ✓
export const REVENUE_DATA = [
  { name: 'Mon', revenue:  4_900_000, visitors:  49 },
  { name: 'Tue', revenue:  5_670_000, visitors:  54 },
  { name: 'Wed', revenue:  5_340_000, visitors:  52 },
  { name: 'Thu', revenue:  7_080_000, visitors:  63 },
  { name: 'Fri', revenue: 13_080_000, visitors: 100 },
  { name: 'Sat', revenue: 15_800_000, visitors: 110 },
  { name: 'Sun', revenue: 10_680_000, visitors:  89 },
];

export const TRANSLATIONS = {
  ru: {
    dashboard: 'Дашборд',
    sales: 'Продажи',
    operations: 'Операции',
    financial: 'Финансы',
    reviews: 'Отзывы',
    loyalty: 'Лояльность',
    reports: 'Отчёты',
    settings: 'Настройки',
    compare: 'Сравнение',
    branch: 'Филиал',
    more: 'Ещё',
    about: 'О Компании',
    logout: 'Выход',
    welcome: 'Добро пожаловать в TRACE',
    subtitle: 'Единая платформа ресторанной аналитики',
    login: 'Войти',
    password: 'Пароль',
    remember_me: 'Запомнить меня',
    loading: 'Загрузка...',
    enter_system: 'Войти в Систему',
    legal_agree_prefix: 'Продолжая, вы соглашаетесь с',
    legal_privacy: 'Политикой конфиденциальности',
    legal_and: 'и',
    legal_terms: 'Условиями использования',
    powered_by: 'Разработано',
    today: 'Сегодня',
    week: '7 Дней',
    month: 'Месяц',
    askAI: 'AI Ассистент',
    aiPlaceholder: 'Задайте вопрос по текущему разделу...',
    download: 'Скачать',
    edit: 'Изменить',
    save: 'Сохранить',
    filter: 'Фильтр',
    search: 'Поиск...',
    date: 'Дата',
    action: 'Действие',
    view_all: 'Смотреть все',
    orders: 'Заказов',
    revenue: 'Выручка',
    total_revenue: 'Выручка',
    avg_check: 'Средний чек',
    guests_count: 'Блюд',
    food_cost: 'Food Cost',
    labor_cost: 'Labor Cost',
    nps_score: 'NPS',
    review_rating: 'Рейтинг',
    revenue_trend: 'Динамика Выручки',
    hall_occupancy: 'Загрузка Зала',
    occupied: 'Занято',
    reserved: 'Бронь',
    rfm_segments: 'Сегменты RFM',
    top_selling: 'Топ Продаж',
    notifications: 'Уведомления',
    integrations: 'Интеграции',
    avg_rating: 'Средний рейтинг',
    total_reviews: 'Всего отзывов',
    positive: 'Положительных',
    sentiment: 'Тональность',
    reply: 'Ответить',
    new_reviews: 'Новые отзывы',
    latest_reviews: 'Последние отзывы',
    all: 'Все',
    ai_reputation_analysis: 'Анализ репутации AI',
    top_praises: 'Топ похвал',
    top_complaints: 'Топ жалоб',
    ai_recommendation: 'Рекомендация AI',
    branch_leaderboard: 'Лидерборд филиалов',
    ltv_analysis: 'Анализ LTV',
    category_perf: 'Эффективность Категорий',
    ai_recs: 'Рекомендации AI',
    price_elasticity: 'Эластичность Цен',
    underperforming: 'Аутсайдеры',
    apply: 'Применить',
    avg_service_time: 'Среднее время стола',
    waste: 'Списания',
    staff_active: 'Персонал',
    hall_heatmap: 'Тепловая карта зала',
    staff_perf: 'Эффективность персонала',
    pl_structure: 'Структура P&L',
    profit_forecast: 'Прогноз Прибыли',
    fc_details: 'Детализация Фуд Кост',
    ideal: 'Идеал',
    actual: 'Факт',
    variance: 'Откл.',
    system_config: 'Конфигурация Системы',
    profile: 'Профиль',
    notifications_settings: 'Уведомления',
    data_sources: 'Источники Данных',
    general: 'Общее',
    connect: 'Подключить',
    disconnect: 'Отключить',
    sync_now: 'Синхронизировать',
    feature_coming_soon: 'Функция скоро будет доступна',
    notifications_cleared: 'Уведомления очищены',
    report_downloaded: 'Отчет скачан',
    data_refreshed: 'Данные обновлены',
    settings_saved: 'Настройки сохранены',
    message_sent: 'Сообщение отправлено',
    item_added: 'Товар добавлен',
    filter_applied: 'Фильтр применен',
    action_completed: 'Действие выполнено успешно',
    date_changed: 'Период изменен: ',
    id_label: 'ID:',
    name: 'Имя',
    role: 'Роль',
    avg_time: 'Среднее Время',
    category: 'Категория',
    ideal_cost: 'Идеальная Стоимость',
    actual_cost: 'Фактическая Стоимость',
    analyze: 'Анализ',
    quick_export: 'Быстрый Экспорт',
    download_today_summary: 'Скачать сводку за сегодня (PDF)',
    schedule_report: 'Запланировать Отчет',
    configure_auto_email: 'Настроить автоматическую рассылку',
    share_access: 'Поделиться Доступом',
    send_link_accountant: 'Отправить ссылку бухгалтеру',
    email_reports: 'Отчёты',
    email_reports_desc: 'Ежедневная сводка по выручке, заказам и топ-блюдам — на почту или в Telegram каждое утро',
    nav_settings_title: 'Навигация',
    nav_settings_desc: 'Выберите, как показывать меню на компьютере и телефоне',
    nav_style_desktop: 'На компьютере',
    nav_style_top: 'Сверху',
    nav_style_side: 'Сбоку',
    nav_style_mobile: 'На телефоне',
    nav_style_bottom_tabs: 'Нижняя панель',
    nav_style_drawer: 'Меню по кнопке',
    pages_visibility_title: 'Разделы',
    pages_visibility_desc: 'Скройте разделы, которые вы не используете — они пропадут из меню на всех устройствах',
    page_locked_note: 'Всегда виден',
    default_page_title: 'Стартовая страница',
    default_page_desc: 'Какой раздел открывать первым после входа',
    accent_title: 'Цвет акцента',
    accent_desc: 'Цвет кнопок, активных пунктов меню и выделений',
    logo_title: 'Логотип',
    logo_desc: 'Свой логотип вместо надписи TRACE в шапке и меню',
    logo_upload: 'Загрузить логотип',
    logo_change: 'Заменить',
    logo_remove: 'Убрать',
    logo_uploading: 'Загрузка...',
    email_address: 'Email',
    channel_label: 'Канал',
    channel_email: 'Email',
    channel_telegram: 'Telegram',
    connect_telegram: 'Подключить Telegram',
    relink_telegram: 'Переподключить',
    telegram_connected: 'Telegram подключён',
    telegram_not_connected: 'Telegram не подключён — нажмите «Подключить», затем «Start» в боте',
    report_frequency: 'Частота',
    freq_daily: 'Ежедневно',
    freq_weekly: 'Раз в неделю (пн)',
    enable_reports: 'Включить рассылку',
    send_test_email: 'Отправить тест',
    test_email_sent: 'Тестовое письмо отправлено',
    report_subscription_saved: 'Настройки рассылки сохранены',
    last_sent: 'Последняя отправка',
    never: 'не было',
    report_type_label: 'Тип отчёта',
    daily_summary_label: 'Сводка по продажам',
    financial_summary_label: 'Финансовый отчёт (P&L)',
    send_hour_label: 'Время отправки',
    add_subscription: 'Добавить рассылку',
    remove_subscription: 'Удалить',
    no_subscriptions: 'Рассылок пока нет — добавьте первую',
    report_archive: 'Архив Отчетов',
    daily_reports_email: 'Ежедневные Отчеты по Email',
    critical_anomalies: 'Критические Аномалии (Push)',
    new_reviews_alert: 'Оповещение о Новых Отзывах',
    system_updates: 'Обновления Системы',
    toggle_setting: 'Переключить настройку',
    email: 'Email',
    super_administrator: 'Супер Администратор',
    owner: 'Владелец',
    manage_integrations: 'Управление внешними интеграциями и потоками данных.',
    last_sync: 'Последняя Синхронизация:',
    view_full_menu: 'Смотреть полное меню',
    vs_last_period: 'vs прошлый период',
    now: 'Сейчас',
    mon: 'Пн',
    tue: 'Вт',
    wed: 'Ср',
    thu: 'Чт',
    fri: 'Пт',
    sat: 'Сб',
    sun: 'Вс',
    // iiko-specific
    cash_shift: 'Кассовая Смена',
    shift_open: 'Открыта',
    shift_closed: 'Закрыта',
    cashier: 'Кассир',
    shift_revenue: 'Выручка смены',
    collections: 'Изъятий',
    stop_list: 'Стоп-Лист',
    stopped_at: 'Остановлено',
    active_orders: 'Активные Заказы',
    ticket_time: 'Открыт, мин',
    order_status_cooking: 'Готовится',
    order_status_waiting: 'Ожидает',
    order_status_ready: 'Готово',
    invoices: 'Накладные',
    writeoffs: 'Акты Списания',
    inventory: 'Инвентаризация',
    supplier: 'Поставщик',
    invoice_amount: 'Сумма',
    invoice_status_posted: 'Проведена',
    invoice_status_draft: 'Черновик',
    shortage: 'Недостача',
    surplus: 'Излишек',
    last_inventory: 'Последняя инвентаризация',
    abc_analysis: 'ABC Анализ',
    hourly_revenue: 'Выручка по часам',
    category_breakdown: 'По Категориям',
    margin: 'Маржа',
    share: 'Доля',
    items_count: 'Позиций',
    olap_reports: 'OLAP Отчёты',
    report_sales_by_dish: 'Продажи по блюдам',
    report_sales_by_cat: 'Продажи по категориям',
    report_employees: 'Отчёт по сотрудникам',
    report_stock: 'Складской отчёт',
    report_writeoffs: 'Акты списания',
    report_shifts: 'Кассовые смены',
    report_pl: 'Отчёт P&L',
    report_gl: 'Сводка по счетам (GL)',
    report_invoices: 'Накладные поставщиков',
    report_abc: 'ABC-анализ меню',
    report_hourly: 'Продажи по часам',
    report_staff_profit: 'Рентабельность персонала',
    report_staff_abc: 'ABC-анализ официантов',
    report_voids: 'Отмены и удаления',
    report_table_revenue: 'Выручка по столам',
    report_delivery: 'Заказы на доставку',
    report_olap_builder: 'OLAP конструктор',
    generate: 'Сформировать',
  },
  en: {
    dashboard: 'Dashboard',
    sales: 'Sales',
    operations: 'Operations',
    financial: 'Finance',
    reviews: 'Reviews',
    loyalty: 'Loyalty',
    reports: 'Reports',
    settings: 'Settings',
    compare: 'Compare',
    branch: 'Branch',
    more: 'More',
    about: 'About Us',
    logout: 'Logout',
    welcome: 'Welcome to TRACE',
    subtitle: 'Unified Restaurant Intelligence Platform',
    login: 'Login',
    password: 'Password',
    remember_me: 'Remember me',
    loading: 'Loading...',
    enter_system: 'Enter System',
    legal_agree_prefix: 'By continuing, you agree to the',
    legal_privacy: 'Privacy Policy',
    legal_and: 'and',
    legal_terms: 'Terms of Use',
    powered_by: 'Powered by',
    today: 'Today',
    week: '7 Days',
    month: 'Month',
    askAI: 'AI Assistant',
    aiPlaceholder: 'Ask a question about this section...',
    download: 'Download',
    edit: 'Edit',
    save: 'Save',
    filter: 'Filter',
    search: 'Search...',
    date: 'Date',
    action: 'Action',
    view_all: 'View All',
    orders: 'Orders',
    revenue: 'Revenue',
    total_revenue: 'Total Revenue',
    avg_check: 'Avg Check',
    guests_count: 'Dishes sold',
    food_cost: 'Food Cost',
    labor_cost: 'Labor Cost',
    nps_score: 'NPS',
    review_rating: 'Rating',
    revenue_trend: 'Revenue Trend',
    hall_occupancy: 'Hall Occupancy',
    occupied: 'Occupied',
    reserved: 'Reserved',
    rfm_segments: 'RFM Segments',
    top_selling: 'Top Selling',
    notifications: 'Notifications',
    integrations: 'Integrations',
    avg_rating: 'Avg Rating',
    total_reviews: 'Total Reviews',
    positive: 'Positive',
    sentiment: 'Sentiment',
    reply: 'Reply',
    new_reviews: 'New Reviews',
    latest_reviews: 'Latest Reviews',
    all: 'All',
    ai_reputation_analysis: 'AI Reputation Analysis',
    top_praises: 'Top Praises',
    top_complaints: 'Top Complaints',
    ai_recommendation: 'AI Recommendation',
    branch_leaderboard: 'Branch Leaderboard',
    ltv_analysis: 'LTV Analysis',
    category_perf: 'Category Performance',
    ai_recs: 'AI Recommendations',
    price_elasticity: 'Price Elasticity',
    underperforming: 'Underperforming',
    apply: 'Apply',
    avg_service_time: 'Avg Table Time',
    waste: 'Waste',
    staff_active: 'Staff Active',
    hall_heatmap: 'Hall Heatmap',
    staff_perf: 'Staff Performance',
    pl_structure: 'P&L Structure',
    profit_forecast: 'Profit Forecast',
    fc_details: 'Food Cost Details',
    ideal: 'Ideal',
    actual: 'Actual',
    variance: 'Var.',
    system_config: 'System Configuration',
    profile: 'Profile',
    notifications_settings: 'Notifications',
    data_sources: 'Data Sources',
    general: 'General',
    connect: 'Connect',
    disconnect: 'Disconnect',
    sync_now: 'Sync Now',
    feature_coming_soon: 'Feature coming soon',
    notifications_cleared: 'Notifications cleared',
    report_downloaded: 'Report downloaded',
    data_refreshed: 'Data refreshed',
    settings_saved: 'Settings saved',
    message_sent: 'Message sent',
    item_added: 'Item added',
    filter_applied: 'Filter applied',
    action_completed: 'Action completed successfully',
    date_changed: 'Period changed: ',
    id_label: 'ID:',
    name: 'Name',
    role: 'Role',
    avg_time: 'Avg Time',
    category: 'Category',
    ideal_cost: 'Ideal Cost',
    actual_cost: 'Actual Cost',
    analyze: 'Analyze',
    quick_export: 'Quick Export',
    download_today_summary: 'Download today\'s summary (PDF)',
    schedule_report: 'Schedule Report',
    configure_auto_email: 'Configure auto-email delivery',
    share_access: 'Share Access',
    send_link_accountant: 'Send link to accountant',
    email_reports: 'Reports',
    email_reports_desc: 'Daily summary of revenue, orders and top dishes — by email or Telegram every morning',
    nav_settings_title: 'Navigation',
    nav_settings_desc: 'Choose how the menu appears on desktop and phone',
    nav_style_desktop: 'On desktop',
    nav_style_top: 'Top bar',
    nav_style_side: 'Sidebar',
    nav_style_mobile: 'On phone',
    nav_style_bottom_tabs: 'Bottom tabs',
    nav_style_drawer: 'Menu button',
    pages_visibility_title: 'Pages',
    pages_visibility_desc: "Hide pages you don't use — they'll disappear from the menu on every device",
    page_locked_note: 'Always visible',
    default_page_title: 'Start page',
    default_page_desc: 'Which page opens first after you log in',
    accent_title: 'Accent color',
    accent_desc: 'Color of buttons, active menu items, and highlights',
    logo_title: 'Logo',
    logo_desc: 'Your own logo instead of the TRACE wordmark in the header and menu',
    logo_upload: 'Upload logo',
    logo_change: 'Change',
    logo_remove: 'Remove',
    logo_uploading: 'Uploading...',
    email_address: 'Email',
    channel_label: 'Channel',
    channel_email: 'Email',
    channel_telegram: 'Telegram',
    connect_telegram: 'Connect Telegram',
    relink_telegram: 'Reconnect',
    telegram_connected: 'Telegram connected',
    telegram_not_connected: 'Telegram not connected — click "Connect", then "Start" in the bot',
    report_frequency: 'Frequency',
    freq_daily: 'Daily',
    freq_weekly: 'Weekly (Mon)',
    enable_reports: 'Enable reports',
    send_test_email: 'Send test',
    test_email_sent: 'Test email sent',
    report_subscription_saved: 'Report settings saved',
    last_sent: 'Last sent',
    never: 'never',
    report_type_label: 'Report type',
    daily_summary_label: 'Sales Summary',
    financial_summary_label: 'Financial Report (P&L)',
    send_hour_label: 'Send time',
    add_subscription: 'Add subscription',
    remove_subscription: 'Remove',
    no_subscriptions: 'No subscriptions yet — add one',
    report_archive: 'Report Archive',
    daily_reports_email: 'Daily Reports via Email',
    critical_anomalies: 'Critical Anomalies (Push)',
    new_reviews_alert: 'New Reviews Alert',
    system_updates: 'System Updates',
    toggle_setting: 'Toggle setting',
    email: 'Email',
    super_administrator: 'Super Administrator',
    owner: 'Owner',
    manage_integrations: 'Manage external integrations and data streams.',
    last_sync: 'Last Sync:',
    view_full_menu: 'View Full Menu',
    vs_last_period: 'vs last period',
    now: 'Now',
    mon: 'Mon',
    tue: 'Tue',
    wed: 'Wed',
    thu: 'Thu',
    fri: 'Fri',
    sat: 'Sat',
    sun: 'Sun',
    // iiko-specific
    cash_shift: 'Cash Shift',
    shift_open: 'Open',
    shift_closed: 'Closed',
    cashier: 'Cashier',
    shift_revenue: 'Shift Revenue',
    collections: 'Collections',
    stop_list: 'Stop List',
    stopped_at: 'Stopped at',
    active_orders: 'Active Orders',
    ticket_time: 'Open For',
    order_status_cooking: 'Cooking',
    order_status_waiting: 'Waiting',
    order_status_ready: 'Ready',
    invoices: 'Invoices',
    writeoffs: 'Write-offs',
    inventory: 'Inventory',
    supplier: 'Supplier',
    invoice_amount: 'Amount',
    invoice_status_posted: 'Posted',
    invoice_status_draft: 'Draft',
    shortage: 'Shortage',
    surplus: 'Surplus',
    last_inventory: 'Last Inventory',
    abc_analysis: 'ABC Analysis',
    hourly_revenue: 'Hourly Revenue',
    category_breakdown: 'By Category',
    margin: 'Margin',
    share: 'Share',
    items_count: 'Items',
    olap_reports: 'OLAP Reports',
    report_sales_by_dish: 'Sales by Dish',
    report_sales_by_cat: 'Sales by Category',
    report_employees: 'Employee Report',
    report_stock: 'Stock Report',
    report_writeoffs: 'Write-off Acts',
    report_shifts: 'Cash Shifts',
    report_pl: 'P&L Report',
    report_gl: 'GL Summary',
    report_invoices: 'Supplier Invoices',
    report_abc: 'Menu ABC Analysis',
    report_hourly: 'Hourly Sales',
    report_staff_profit: 'Staff Profitability',
    report_staff_abc: 'Staff ABC Analysis',
    report_voids: 'Voids & Cancellations',
    report_table_revenue: 'Revenue by Table',
    report_delivery: 'Delivery Orders',
    report_olap_builder: 'OLAP Builder',
    generate: 'Generate',
  },
  uz: {
    dashboard: 'Dashboard',
    sales: 'Sotuvlar',
    operations: 'Operatsiyalar',
    financial: 'Moliya',
    reviews: 'Sharhlar',
    loyalty: 'Sadoqat',
    reports: 'Hisobotlar',
    settings: 'Sozlamalar',
    compare: 'Taqqoslash',
    branch: 'Filial',
    more: 'Yana',
    about: 'Kompaniya haqida',
    logout: 'Chiqish',
    welcome: 'TRACE-ga xush kelibsiz',
    subtitle: 'Restoran tahlili uchun yagona platforma',
    login: 'Kirish',
    password: 'Parol',
    remember_me: 'Meni eslab qol',
    loading: 'Yuklanmoqda...',
    enter_system: 'Tizimga kirish',
    legal_agree_prefix: 'Davom etish orqali siz',
    legal_privacy: 'Maxfiylik siyosati',
    legal_and: 'va',
    legal_terms: 'Foydalanish shartlari',
    powered_by: 'Ishlab chiquvchi',
    today: 'Bugun',
    week: '7 kun',
    month: 'Oy',
    askAI: 'AI Yordamchi',
    aiPlaceholder: "Joriy bo'lim bo'yicha savol bering...",
    download: 'Yuklab olish',
    edit: 'Tahrirlash',
    save: 'Saqlash',
    filter: 'Filtr',
    search: 'Qidiruv...',
    date: 'Sana',
    action: 'Amal',
    view_all: "Hammasini ko'rish",
    orders: 'Buyurtmalar',
    revenue: 'Tushum',
    total_revenue: 'Tushum',
    avg_check: "O'rtacha chek",
    guests_count: 'Taomlar',
    food_cost: 'Food Cost',
    labor_cost: 'Labor Cost',
    nps_score: 'NPS',
    review_rating: 'Reyting',
    revenue_trend: 'Tushum dinamikasi',
    hall_occupancy: 'Zal bandligi',
    occupied: 'Band',
    reserved: 'Band qilingan',
    rfm_segments: 'RFM segmentlari',
    top_selling: "Eng ko'p sotilganlar",
    notifications: 'Bildirishnomalar',
    integrations: 'Integratsiyalar',
    avg_rating: "O'rtacha reyting",
    total_reviews: 'Jami sharhlar',
    positive: 'Ijobiy',
    sentiment: 'Kayfiyat',
    reply: 'Javob berish',
    new_reviews: 'Yangi sharhlar',
    latest_reviews: "So'nggi sharhlar",
    all: 'Barchasi',
    ai_reputation_analysis: "AI obro' tahlili",
    top_praises: "Eng ko'p maqtovlar",
    top_complaints: "Eng ko'p shikoyatlar",
    ai_recommendation: 'AI tavsiyasi',
    branch_leaderboard: 'Filiallar reytingi',
    ltv_analysis: 'LTV tahlili',
    category_perf: 'Kategoriyalar samaradorligi',
    ai_recs: 'AI tavsiyalari',
    price_elasticity: 'Narx elastikligi',
    underperforming: 'Past samarali',
    apply: "Qo'llash",
    avg_service_time: "O'rtacha stol vaqti",
    waste: 'Chiqindilar',
    staff_active: 'Faol xodimlar',
    hall_heatmap: 'Zal issiqlik xaritasi',
    staff_perf: 'Xodimlar samaradorligi',
    pl_structure: 'P&L tuzilishi',
    profit_forecast: 'Foyda bashorati',
    fc_details: 'Food Cost tafsilotlari',
    ideal: 'Ideal',
    actual: 'Fakt',
    variance: 'Farq',
    system_config: 'Tizim konfiguratsiyasi',
    profile: 'Profil',
    notifications_settings: 'Bildirishnomalar',
    data_sources: "Ma'lumot manbalari",
    general: 'Umumiy',
    connect: 'Ulash',
    disconnect: 'Uzish',
    sync_now: 'Sinxronlash',
    feature_coming_soon: "Funksiya tez orada qo'shiladi",
    notifications_cleared: 'Bildirishnomalar tozalandi',
    report_downloaded: 'Hisobot yuklab olindi',
    data_refreshed: "Ma'lumotlar yangilandi",
    settings_saved: 'Sozlamalar saqlandi',
    message_sent: 'Xabar yuborildi',
    item_added: "Mahsulot qo'shildi",
    filter_applied: "Filtr qo'llandi",
    action_completed: 'Amal muvaffaqiyatli bajarildi',
    date_changed: "Davr o'zgartirildi: ",
    id_label: 'ID:',
    name: 'Ism',
    role: 'Lavozim',
    avg_time: "O'rtacha vaqt",
    category: 'Kategoriya',
    ideal_cost: 'Ideal qiymat',
    actual_cost: 'Haqiqiy qiymat',
    analyze: 'Tahlil',
    quick_export: 'Tezkor eksport',
    download_today_summary: 'Bugungi xulosani yuklab olish (PDF)',
    schedule_report: 'Hisobotni rejalashtirish',
    configure_auto_email: 'Avtomatik email yuborishni sozlash',
    share_access: 'Ruxsatni ulashish',
    send_link_accountant: 'Buxgalterga havola yuborish',
    email_reports: 'Hisobotlar',
    email_reports_desc: "Tushum, buyurtmalar va eng ko'p sotilgan taomlar bo'yicha kunlik xulosa — pochta yoki Telegram orqali har kuni ertalab",
    nav_settings_title: 'Navigatsiya',
    nav_settings_desc: "Menyu kompyuter va telefonda qanday ko'rinishini tanlang",
    nav_style_desktop: 'Kompyuterda',
    nav_style_top: 'Yuqorida',
    nav_style_side: 'Yon panelda',
    nav_style_mobile: 'Telefonda',
    nav_style_bottom_tabs: 'Pastki panel',
    nav_style_drawer: 'Menyu tugmasi',
    pages_visibility_title: "Bo'limlar",
    pages_visibility_desc: "Foydalanmaydigan bo'limlarni yashiring — ular barcha qurilmalarda menyudan yo'qoladi",
    page_locked_note: 'Doim ko\'rinadi',
    default_page_title: 'Boshlang\'ich sahifa',
    default_page_desc: 'Tizimga kirgandan keyin qaysi sahifa ochilishi',
    accent_title: 'Urg\'u rangi',
    accent_desc: 'Tugmalar, faol menyu bandlari va belgilashlar rangi',
    logo_title: 'Logotip',
    logo_desc: 'Sarlavha va menyudagi TRACE yozuvi o\'rniga o\'z logotipingiz',
    logo_upload: 'Logotip yuklash',
    logo_change: 'Almashtirish',
    logo_remove: "O'chirish",
    logo_uploading: 'Yuklanmoqda...',
    email_address: 'Email',
    channel_label: 'Kanal',
    channel_email: 'Email',
    channel_telegram: 'Telegram',
    connect_telegram: 'Telegramni ulash',
    relink_telegram: 'Qayta ulash',
    telegram_connected: 'Telegram ulandi',
    telegram_not_connected: 'Telegram ulanmagan — "Ulash", so\'ng botda "Start" bosing',
    report_frequency: 'Davriylik',
    freq_daily: 'Har kuni',
    freq_weekly: 'Haftada bir marta (dush.)',
    enable_reports: 'Yuborishni yoqish',
    send_test_email: 'Test yuborish',
    test_email_sent: 'Test xat yuborildi',
    report_subscription_saved: 'Yuborish sozlamalari saqlandi',
    last_sent: 'Oxirgi yuborilgan',
    never: "hali yo'q",
    report_type_label: 'Hisobot turi',
    daily_summary_label: 'Sotuvlar xulosasi',
    financial_summary_label: 'Moliyaviy hisobot (P&L)',
    send_hour_label: 'Yuborish vaqti',
    add_subscription: "Yuborishni qo'shish",
    remove_subscription: "O'chirish",
    no_subscriptions: "Hozircha yuborishlar yo'q — birinchisini qo'shing",
    report_archive: 'Hisobotlar arxivi',
    daily_reports_email: 'Kunlik hisobotlar (Email)',
    critical_anomalies: 'Kritik anomaliyalar (Push)',
    new_reviews_alert: 'Yangi sharhlar haqida ogohlantirish',
    system_updates: 'Tizim yangilanishlari',
    toggle_setting: 'Sozlamani almashtirish',
    email: 'Email',
    super_administrator: 'Bosh administrator',
    owner: 'Egasi',
    manage_integrations: "Tashqi integratsiyalar va ma'lumot oqimlarini boshqarish.",
    last_sync: 'Oxirgi sinxronizatsiya:',
    view_full_menu: "To'liq menyuni ko'rish",
    vs_last_period: 'oldingi davrga nisbatan',
    now: 'Hozir',
    mon: 'Du',
    tue: 'Se',
    wed: 'Cho',
    thu: 'Pa',
    fri: 'Ju',
    sat: 'Sha',
    sun: 'Ya',
    // iiko-specific
    cash_shift: 'Kassa smenasi',
    shift_open: 'Ochiq',
    shift_closed: 'Yopiq',
    cashier: 'Kassir',
    shift_revenue: 'Smena tushumi',
    collections: 'Inkassatsiya',
    stop_list: 'Stop-list',
    stopped_at: "To'xtatilgan",
    active_orders: 'Faol buyurtmalar',
    ticket_time: 'Ochiq, daq',
    order_status_cooking: 'Tayyorlanmoqda',
    order_status_waiting: 'Kutilmoqda',
    order_status_ready: 'Tayyor',
    invoices: 'Hisob-fakturalar',
    writeoffs: 'Hisobdan chiqarish aktlari',
    inventory: 'Inventarizatsiya',
    supplier: 'Yetkazib beruvchi',
    invoice_amount: 'Summa',
    invoice_status_posted: "O'tkazilgan",
    invoice_status_draft: 'Qoralama',
    shortage: 'Kamomad',
    surplus: 'Ortiqcha',
    last_inventory: 'Oxirgi inventarizatsiya',
    abc_analysis: 'ABC tahlili',
    hourly_revenue: 'Soatlik tushum',
    category_breakdown: "Kategoriyalar bo'yicha",
    margin: 'Marja',
    share: 'Ulush',
    items_count: 'Pozitsiyalar',
    olap_reports: 'OLAP hisobotlar',
    report_sales_by_dish: "Taomlar bo'yicha sotuvlar",
    report_sales_by_cat: "Kategoriyalar bo'yicha sotuvlar",
    report_employees: 'Xodimlar hisoboti',
    report_stock: 'Ombor hisoboti',
    report_writeoffs: 'Hisobdan chiqarish aktlari',
    report_shifts: 'Kassa smenalari',
    report_pl: 'P&L hisoboti',
    report_gl: 'Hisoblar (GL) xulosasi',
    report_invoices: "Yetkazib beruvchi hisob-fakturalari",
    report_abc: 'Menyu ABC-tahlili',
    report_hourly: "Soatlik sotuvlar",
    report_staff_profit: 'Xodimlar rentabelligi',
    report_staff_abc: 'Ofitsiantlar ABC-tahlili',
    report_voids: "Bekor qilishlar va o'chirishlar",
    report_table_revenue: 'Stollar boʻyicha tushum',
    report_delivery: "Yetkazib berish buyurtmalari",
    report_olap_builder: 'OLAP konstruktor',
    generate: 'Yaratish',
  }
};